print ("1 - opção 1")
print ("2 - opção 2")
print ("3 - opção 3")
print ("4 - opção 4")
print ("5 - SAIR")
opcao=str.upper(input("Escolha uma opção: "))
input("aperte ENTER para continuar")
while opcao != "SAIR":
    print ("1 - opção 1")
    print ("2 - opção 2")
    print ("3 - opção 3")
    print ("4 - opção 4")
    print ("5 - SAIR")
    opcao=str.upper(input("Escolha uma opção: "))
    input("aperte ENTER para continuar")